DROP DATABASE IF EXISTS flowers WITH (FORCE);

CREATE DATABASE flowers;

ALTER DATABASE flowers OWNER TO flowers;

\c flowers;

-------------------------------------------------
-- USERS
-------------------------------------------------
CREATE TABLE users (
    user_id SERIAL PRIMARY KEY,
    email TEXT NOT NULL UNIQUE,
    username TEXT NOT NULL UNIQUE,
    password TEXT NOT NULL,
    first_name TEXT NOT NULL,
    last_name TEXT NOT NULL,
    phone_number TEXT
);

COMMENT ON TABLE users IS 'Stores authenticated application users';

ALTER TABLE users OWNER TO flowers;

-------------------------------------------------
-- MONITORS
-------------------------------------------------
CREATE TABLE monitors (
    monitor_id SERIAL PRIMARY KEY,
    name TEXT NOT NULL,
    api_key TEXT NOT NULL UNIQUE
);

COMMENT ON TABLE monitors IS 'Stores monitoring devices';

ALTER TABLE monitors OWNER TO flowers;

-------------------------------------------------
-- USERS_MONITORS (Many-to-Many)
-------------------------------------------------
CREATE TABLE users_monitors (
    monitor_id INTEGER NOT NULL REFERENCES monitors(monitor_id) ON DELETE CASCADE,
    user_id INTEGER NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    PRIMARY KEY (monitor_id, user_id)
);

COMMENT ON TABLE users_monitors IS 'Junction table linking users and monitors';

ALTER TABLE users_monitors OWNER TO flowers;

CREATE INDEX idx_users_monitors_user_id ON users_monitors(user_id);

-------------------------------------------------
-- RECORDS
-------------------------------------------------
CREATE TABLE records (
    record_id SERIAL PRIMARY KEY,
    monitor_id INTEGER NOT NULL REFERENCES monitors(monitor_id) ON DELETE CASCADE,
    time TIMESTAMPTZ NOT NULL,
    dehydration_score DOUBLE PRECISION NOT NULL,
    file_path TEXT NOT NULL,
    UNIQUE (monitor_id, time)
);

COMMENT ON TABLE records IS 'Time-series data generated by monitors';

ALTER TABLE records OWNER TO flowers;

CREATE INDEX idx_records_time ON records(time);


-- Create alert_method type
CREATE TYPE alert_method AS ENUM ('email', 'sms');

-------------------------------------------------
-- ALERTS
-------------------------------------------------
CREATE TABLE alerts (
    alert_id SERIAL PRIMARY KEY,
    record_id INTEGER NOT NULL REFERENCES records(record_id) ON DELETE CASCADE,
    alert_type TEXT NOT NULL,
    alert_method alert_method NOT NULL,
    triggered_at TIMESTAMPTZ DEFAULT NOW()
);

COMMENT ON TABLE alerts IS 'Stores dehydration alert history';

ALTER TABLE alerts OWNER TO flowers;
