DROP DATABASE flowers;

CREATE DATABASE flowers;

\c flowers;

CREATE TABLE users (
    user_id SERIAL PRIMARY KEY,
    email TEXT NOT NULL UNIQUE,
    username TEXT NOT NULL UNIQUE,
    password TEXT NOT NULL
);

COMMENT ON TABLE users IS 'Stores application users';

CREATE TABLE monitors (
    monitor_id SERIAL PRIMARY KEY,
    name TEXT NOT NULL
);

COMMENT ON TABLE monitors IS 'Stores monitoring devices or entities';

CREATE TABLE users_monitors (
    monitor_id INTEGER NOT NULL REFERENCES monitors(monitor_id) ON DELETE CASCADE,
    user_id INTEGER NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    PRIMARY KEY (monitor_id, user_id)
);

COMMENT ON TABLE users_monitors IS 'Junction table: which users are associated with which monitors';

CREATE INDEX idx_users_monitors_user_id ON users_monitors(user_id);

CREATE TABLE records (
    record_id SERIAL PRIMARY KEY,
    monitor_id INTEGER NOT NULL REFERENCES monitors(monitor_id) ON DELETE CASCADE,
    time TIMESTAMPTZ NOT NULL,
    value DOUBLE PRECISION NOT NULL,
    file_path TEXT,
    UNIQUE (monitor_id, time)
);

COMMENT ON TABLE records IS 'Data records generated by monitors';

CREATE INDEX idx_records_time ON records(time);
-- UNIQUE(monitor_id, time) provides an index on (monitor_id, time) for per-monitor and time-range lookups

