\c flowers;

BEGIN;

-- Truncate tables in correct order (respecting foreign key constraints)
TRUNCATE TABLE records, users_monitors, monitors, users RESTART IDENTITY CASCADE;

-- Sequences are automatically reset by RESTART IDENTITY above

INSERT INTO users (email, username, password) VALUES
('grower1@farm.com', 'green_valley', '$2a$12$oYYHWhjYpM7HDEJEbXWeAu0dNKK1rixiofSKeLLBPAmL1REkJSvSO'), -- grower1pw
('grower2@farm.com', 'sunrise_farms', '$2a$12$PwkVHXfBQG74SH622qiIUeWDXC9BeTX2ZGtZZ0WX1zCZnERbdzOry'); -- grower2pw

INSERT INTO monitors (name) VALUES
('dehydrating_device'),
('healthy_device'),
('warning_device');

INSERT INTO users_monitors (user_id, monitor_id) VALUES
(1, 1),  -- green_valley owns dehydrating_device
(1, 2),  -- green_valley owns healthy_device
(2, 3);  -- sunrise_farms owns warning_device

-- value = health score (0.0 = severely stressed/dehydrated, 1.0 = fully healthy)
-- Filenames below are generated by `npm run seed-images` (scripts/seed-demo-images.js).
-- Run that script after seeding the DB to populate imgs/ for local testing.
INSERT INTO records (monitor_id, time, value, file_path) VALUES
------------------------------------------------------------------------------
-- dehydrating_device (monitor_id = 1)
-- declining health score – flower is becoming increasingly dehydrated
(1, NOW() - INTERVAL '180 minutes', 0.35, '/imgs/1/2026-01-15T07-00-00.000Z.jpg'),
(1, NOW() - INTERVAL '170 minutes', 0.32, '/imgs/1/2026-01-15T07-10-00.000Z.jpg'),
(1, NOW() - INTERVAL '160 minutes', 0.28, '/imgs/1/2026-01-15T07-20-00.000Z.jpg'),
(1, NOW() - INTERVAL '150 minutes', 0.24, '/imgs/1/2026-01-15T07-30-00.000Z.jpg'),
(1, NOW() - INTERVAL '140 minutes', 0.20, '/imgs/1/2026-01-15T07-40-00.000Z.jpg'),
(1, NOW() - INTERVAL '130 minutes', 0.17, '/imgs/1/2026-01-15T07-50-00.000Z.jpg'),
(1, NOW() - INTERVAL '120 minutes', 0.14, '/imgs/1/2026-01-15T08-00-00.000Z.jpg'),
(1, NOW() - INTERVAL '110 minutes', 0.11, '/imgs/1/2026-01-15T08-10-00.000Z.jpg'),
(1, NOW() - INTERVAL '100 minutes', 0.09, '/imgs/1/2026-01-15T08-20-00.000Z.jpg'),
(1, NOW() - INTERVAL  '90 minutes', 0.07, '/imgs/1/2026-01-15T08-30-00.000Z.jpg'),
(1, NOW() - INTERVAL  '80 minutes', 0.05, '/imgs/1/2026-01-15T08-40-00.000Z.jpg'),
(1, NOW() - INTERVAL  '70 minutes', 0.04, '/imgs/1/2026-01-15T08-50-00.000Z.jpg'),
------------------------------------------------------------------------------
-- healthy_device (monitor_id = 2)
-- stable high health score – flower is well hydrated
(2, NOW() - INTERVAL '180 minutes', 0.90, '/imgs/2/2026-01-15T07-00-00.000Z.jpg'),
(2, NOW() - INTERVAL '160 minutes', 0.89, '/imgs/2/2026-01-15T07-20-00.000Z.jpg'),
(2, NOW() - INTERVAL '140 minutes', 0.91, '/imgs/2/2026-01-15T07-40-00.000Z.jpg'),
(2, NOW() - INTERVAL '120 minutes', 0.88, '/imgs/2/2026-01-15T08-00-00.000Z.jpg'),
(2, NOW() - INTERVAL '100 minutes', 0.90, '/imgs/2/2026-01-15T08-20-00.000Z.jpg'),
(2, NOW() - INTERVAL  '80 minutes', 0.92, '/imgs/2/2026-01-15T08-40-00.000Z.jpg'),
(2, NOW() - INTERVAL  '60 minutes', 0.91, '/imgs/2/2026-01-15T09-00-00.000Z.jpg'),
(2, NOW() - INTERVAL  '40 minutes', 0.93, '/imgs/2/2026-01-15T09-20-00.000Z.jpg'),
(2, NOW() - INTERVAL  '20 minutes', 0.94, '/imgs/2/2026-01-15T09-40-00.000Z.jpg'),
------------------------------------------------------------------------------
-- warning_device (monitor_id = 3)
-- slowly declining health score – borderline, needs attention
(3, NOW() - INTERVAL '180 minutes', 0.58, '/imgs/3/2026-01-15T07-00-00.000Z.jpg'),
(3, NOW() - INTERVAL '160 minutes', 0.55, '/imgs/3/2026-01-15T07-20-00.000Z.jpg'),
(3, NOW() - INTERVAL '140 minutes', 0.52, '/imgs/3/2026-01-15T07-40-00.000Z.jpg'),
(3, NOW() - INTERVAL '120 minutes', 0.48, '/imgs/3/2026-01-15T08-00-00.000Z.jpg'),
(3, NOW() - INTERVAL '100 minutes', 0.45, '/imgs/3/2026-01-15T08-20-00.000Z.jpg'),
(3, NOW() - INTERVAL  '80 minutes', 0.42, '/imgs/3/2026-01-15T08-40-00.000Z.jpg'),
(3, NOW() - INTERVAL  '60 minutes', 0.39, '/imgs/3/2026-01-15T09-00-00.000Z.jpg'),
(3, NOW() - INTERVAL  '40 minutes', 0.36, '/imgs/3/2026-01-15T09-20-00.000Z.jpg'),
(3, NOW() - INTERVAL  '20 minutes', 0.32, '/imgs/3/2026-01-15T09-40-00.000Z.jpg');

COMMIT;

